version: '3'

services:
  postgres:
    container_name: unichat-postgres
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: unichat
      POSTGRES_DB: unichat
    restart: on-failure
    ports:
      - 5432:5432

  back-end:
    restart: on-failure
    depends_on: 
      - postgres
    container_name: unichat-backend
    build: ./back-end
    links:
      - postgres:postgres
    ports:
      - 3333:3333
    volumes:
      - ./back-end:/var/www/back-end:cached
      - ./back-end/node_modules
    command: yarn start:dev

  front-end:
    depends_on:
      - back-end
    container_name: unichat-frontend
    build:
      context: ./front-end
    volumes:
      - ./front-end:/var/www/front-end:cached
      - ./front-end/node_modules
    ports:
      - 3000:3000
    